html, body, #map-canvas {
    height: 100%;
    margin: 0px;
    padding: 0px;
}

button::-moz-focus-inner {
  border: 0;
}

.quakeInfo {
    height: 400px;
    overflow: auto;
}

.navbar-default
{
    margin-bottom: 1px;
}
.navbar-form .input-group > .form-control {
  width: 100%;
}

.modal-title {
    border-style: none;
    border-bottom: solid #FF5252;
}

.btn-circle {
  width: 30px;
  height: 30px;
  text-align: center;
  padding: 6px 0;
  font-size: 12px;
  line-height: 1.428571429;
  border-radius: 15px;
}

.btn-circle.btn-lg {
  width: 50px;
  height: 50px;
  padding: 10px 12px 16px 12px;
  font-size: 25px;
  line-height: 1.33;
  border-radius: 25px;
}

.btn {
  position: absolute;
  bottom: 18px;
  right: 18px;
}

.btn:focus {
  outline: none;
}

.btn:focus,.btn:active:focus,.btn.active:focus,
.btn.focus,.btn:active.focus,.btn.active.focus {
    outline: none;
}

.btn-danger{
    background-image: -webkit-radial-gradient(circle, #FF5252 80%, #cb171e 81%);
    background-image: -o-radial-gradient(circle, #FF5252 80%, #cb171e 81%);
    background-image: radial-gradient(circle, #FF5252 80%, #cb171e 81%);
}  